# 도커 컴포즈 파일에 변경 생기면 바로 인스턴스에 반영하기
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - swyp-network

  app:
    image: jdagon2000/swyp-team7
    container_name: swyp-app
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    networks:
      - swyp-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - swyp-network

volumes:
  mysql_data:

networks:
  swyp-network:
