spring:
  datasource:
    url: jdbc:mysql://db:3306/swyp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jwt:
    access-key: ${JWT_ACCESS_KEY}
